In [7]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [8]:
#2. Print the NUMPY version and the configuration.

In [12]:
print(np.__version__)
print(np.show_config())

1.16.2
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']

In [ ]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
#4. Print a.

In [14]:
a = np.random.random((2,3,5))
print(a)

[[[0.82928902 0.08223051 0.58729245 0.75976469 0.67204608]
  [0.09785964 0.84718352 0.5213028  0.32597347 0.58325779]
  [0.91031253 0.19963566 0.14934392 0.28894081 0.01292148]]

 [[0.64936912 0.05082651 0.0248128  0.600971   0.25646672]
  [0.05364725 0.17483004 0.87810823 0.57750982 0.34764327]
  [0.05736683 0.84300541 0.71192528 0.11402229 0.20481478]]]


In [ ]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
#6. Print b.

In [16]:
b = np.random.random((5,2,3))
b.fill(1)
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [20]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size)
print(b.size)

if a.size==b.size:
    print("a and b have the same size")
else:
    print("a and b have not the same size")



30
30
a and b have the same size


In [ ]:
#8. Are you able to add a and b? Why or why not?

In [23]:
#We cannot add a and b because they do not broadcast same shapes.
print(a.shape)
print(b.shape)
print(np.add(a, b))

(2, 3, 5)
(5, 2, 3)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [44]:
#c=b.transpose()
#print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [47]:
c=np.reshape(b, (2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [48]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [49]:
d=np.add(a,c)
print(d)

#it is working because now a and c have the same shape.

[[[1.82928902 1.08223051 1.58729245 1.75976469 1.67204608]
  [1.09785964 1.84718352 1.5213028  1.32597347 1.58325779]
  [1.91031253 1.19963566 1.14934392 1.28894081 1.01292148]]

 [[1.64936912 1.05082651 1.0248128  1.600971   1.25646672]
  [1.05364725 1.17483004 1.87810823 1.57750982 1.34764327]
  [1.05736683 1.84300541 1.71192528 1.11402229 1.20481478]]]


In [ ]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [52]:
print(a)

[[[0.82928902 0.08223051 0.58729245 0.75976469 0.67204608]
  [0.09785964 0.84718352 0.5213028  0.32597347 0.58325779]
  [0.91031253 0.19963566 0.14934392 0.28894081 0.01292148]]

 [[0.64936912 0.05082651 0.0248128  0.600971   0.25646672]
  [0.05364725 0.17483004 0.87810823 0.57750982 0.34764327]
  [0.05736683 0.84300541 0.71192528 0.11402229 0.20481478]]]


In [54]:
print(d)

[[[1.82928902 1.08223051 1.58729245 1.75976469 1.67204608]
  [1.09785964 1.84718352 1.5213028  1.32597347 1.58325779]
  [1.91031253 1.19963566 1.14934392 1.28894081 1.01292148]]

 [[1.64936912 1.05082651 1.0248128  1.600971   1.25646672]
  [1.05364725 1.17483004 1.87810823 1.57750982 1.34764327]
  [1.05736683 1.84300541 1.71192528 1.11402229 1.20481478]]]


In [56]:
d=a+1
print(d)

[[[1.82928902 1.08223051 1.58729245 1.75976469 1.67204608]
  [1.09785964 1.84718352 1.5213028  1.32597347 1.58325779]
  [1.91031253 1.19963566 1.14934392 1.28894081 1.01292148]]

 [[1.64936912 1.05082651 1.0248128  1.600971   1.25646672]
  [1.05364725 1.17483004 1.87810823 1.57750982 1.34764327]
  [1.05736683 1.84300541 1.71192528 1.11402229 1.20481478]]]


In [ ]:
#12. Multiply a and c. Assign the result to e.

In [57]:
e=a*c
print(e)

[[[0.82928902 0.08223051 0.58729245 0.75976469 0.67204608]
  [0.09785964 0.84718352 0.5213028  0.32597347 0.58325779]
  [0.91031253 0.19963566 0.14934392 0.28894081 0.01292148]]

 [[0.64936912 0.05082651 0.0248128  0.600971   0.25646672]
  [0.05364725 0.17483004 0.87810823 0.57750982 0.34764327]
  [0.05736683 0.84300541 0.71192528 0.11402229 0.20481478]]]


In [ ]:
#13. Does e equal to a? Why or why not?

In [71]:
# e equals to a as c=1.
if a.any() == e.any():
    print("it's a match")

if a.all() == e.all():
    print("it's a match")


it's a match
it's a match


In [ ]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [79]:
d_max= np.amax(d)
d_min= np.amin(d) 
d_mean= np.mean(d) 

print(d_max)
print(d_min)
print(d_mean)

1.9103125328401858
1.0129214831441793
1.413755790594325


In [ ]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [90]:
f= np.empty([2,3,5])
print(f)

[[[0.82928902 0.08223051 0.58729245 0.75976469 0.67204608]
  [0.09785964 0.84718352 0.5213028  0.32597347 0.58325779]
  [0.91031253 0.19963566 0.14934392 0.28894081 0.01292148]]

 [[0.64936912 0.05082651 0.0248128  0.600971   0.25646672]
  [0.05364725 0.17483004 0.87810823 0.57750982 0.34764327]
  [0.05736683 0.84300541 0.71192528 0.11402229 0.20481478]]]


In [89]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.


In [108]:

f[(f > d_min) & (f< d_mean)] = 25
f[(f > d_mean) & (f< d_max)] = 75
f[f == d_mean] = 50
f[f == d_min] = 0
f[f == d_max] = 100
print(f)

[[[25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]

 [[25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]]


In [107]:
""
#17. Print d and f. Do you have your expected f?
#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

SyntaxError: invalid syntax (<ipython-input-107-ecf1426f5966>, line 3)

In [ ]:
# Yes!

In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""